spring.datasource.url=jdbc:postgresql://localhost:5432/factus_db
spring.datasource.username=postgres
spring.datasource.password=3184018708aA.
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración adicional
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
