spring.datasource.url=jdbc:postgresql://localhost:5434/factus_db
spring.datasource.username=postgres
spring.datasource.password=3184018708aA.
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci�n adicional
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

